#
# This source file is part of the Stanford CardinalKit Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v1
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v1
  buildandtestiosapp:
    name: Build and Test iOS App
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
    - name: Cache Firebase Emulators
      uses: actions/cache@v3
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
    - name: Setup NodeJS
      uses: actions/setup-node@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Install Firebase CLI Tools
      run: npm install -g firebase-tools
    - name: Build and Test Example App
      run: |
          firebase emulators:exec 'bundler install && bundle exec fastlane test'
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TemplateApplication.xcresult
        path: TemplateApplication.xcresult
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        xcode: true
        xcode_archive_path: TemplateApplication.xcresult
